remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Akshita Lakkad"
description: "Software Engineer | Master's in Computer Science at NYU | Experience in Machine Learning and Cloud Computing"
